### ISSUE TITLE
Include examples and test directories in release tarball

### ISSUE THREAD

**Issue by paddatrapper** [savonet/ocaml-ffmpeg#23]
Can you please include the `examples` and `test` directories in the release tarball? Currently the project will not build because the Makefile references these in the `test` target

**Comment by gndl** [comment]
Thanks for the bug report.
I did a pull request (#24 ) to correct the problem.

**Comment by paddatrapper** [comment]
Thanks!

**Comment by toots** [comment]
Just released the fixed package!
