### ISSUE TITLE
Broken homepage link

### ISSUE THREAD

**Issue by mikaello** [savonet/ocaml-ffmpeg#37]
The link `http://liquidsoap.fm` is broken, and should be removed or replaced with a new one.

![Skjermbilde 2020-01-30 kl  17 39 52](https://user-images.githubusercontent.com/2505178/73470067-9eaceb80-4387-11ea-9262-6a5ac24f514e.png)

The new page seems to be: `https://liquidsoap.info`, is this correct?

**Comment by toots** [comment]
Thanks!
