### ISSUE TITLE
v0.4.3: Missing implementations when compiling

### ISSUE THREAD

**Issue by rand00** [savonet/ocaml-ffmpeg#48]
I installed ffmpeg through opam, which gives me version 0.4.3. I just depend on `ffmpeg` in my dune file, but get the following error when compiling:

``` bash
$ ./install.sh
Error: No implementations provided for the following modules:
         Avutil referenced from bin/clients/n/.n.eobjs/native/n.cmx
         Avdevice referenced from bin/clients/n/.n.eobjs/native/n.cmx
         Av referenced from bin/clients/n/.n.eobjs/native/n.cmx
Done: 524/529 (jobs: 1)ERROR
```
This happened both on 4.11.1+flambda and 4.07.1 - and I'm running arch linux

**Comment by toots** [comment]
This is really old. Closing, feel free to reopen if it still happens.
